name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/extensions-functional.sln
    
    - name: Build
      run: dotnet build src/extensions-functional.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test src/extensions-functional.sln --configuration Release --no-build --verbosity normal
    
    - name: Extract version
      id: extract_version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
    
    - name: Pack
      run: dotnet pack src/extensions-functional.sln --no-build --configuration Release /p:Version=${{ steps.extract_version.outputs.VERSION }} --output ./packages
    
    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        draft: false
        prerelease: ${{ contains(steps.extract_version.outputs.VERSION, '-') }}
        name: Release ${{ steps.extract_version.outputs.VERSION }}
        files: ./packages/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    # Uncomment this when ready to publish to NuGet.org
    # - name: Publish to NuGet.org
    #   run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate